name: Release
on:
  workflow_dispatch:
jobs:
  devcontainer-build:
    uses: datajoint/dj-gha-workflows/.github/workflows/devcontainer-build.yaml@main
  devcontainer-publish:
    needs: 
      - devcontainer-build
    uses: datajoint/dj-gha-workflows/.github/workflows/devcontainer-publish.yaml@main
    secrets:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
